### ISSUE TITLE
weblogic解密脚本的btol、ltob是什么方法

### ISSUE THREAD

**Issue by vc1** [L-codes/ctf-scripts#1]
https://github.com/L-codes/ctf-scripts/blob/master/crypto/weblogic_password.py#L62

**Comment by L-codes** [comment]
python的这个版本不是我写的，weblogic_password.rb才是我重写的。
python的版本有很多BUG，然后你问的btol和ltob不难看出是 binary to long 和 long to binary

**Comment by vc1** [comment]
> python的这个版本不是我写的，weblogic_password.rb才是我重写的。
> python的版本有很多BUG，然后你问的btol和ltob不难看出是 binary to long 和 long to binary

PBKDF3算法有什么资料吗，没找到算法原理，各种加密库里也没这个，我是想把解密移植到网页js里

**Comment by L-codes** [comment]
这个 python/ruby 的版本就已经算法原理和具体实现了，ruby 的版本要精化很多，你可以对照重写
